FROM node:16-alpine
WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./client/package*.json ./packages/client/

RUN npm ci -w ./client

COPY .client ./packages/client

ARG VITE_API_KEY 
ENV VITE_APP_BASE_URL=${VITE_API_KEY }

RUN npm run build -w ./client
EXPOSE 5173

CMD [ "npx", "serve", "-s", "/client/build" ]